os: linux
dist: xenial
language: python
python:
    - "3.8"
cache:
    directories:
        - "~/.platformio"
install:
    - pip install -U platformio
    - platformio update
script:
    - platformio run
